[project]
name = "fastrouters"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.2",
    "fastapi>=0.115.12",
    "pydantic>=2.11.3",
    "sqlalchemy>=2.0.40",
    "sqlmodel>=0.0.24",
]
